# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ECE385/urbana_ddr3_provided/urbana_ddr3.xdc

# XDC: imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc

# IP: ip/char2_rom/char2_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==char2_rom || ORIG_REF_NAME==char2_rom} -quiet] -quiet

# IP: ip/taiki_rom/taiki_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==taiki_rom || ORIG_REF_NAME==taiki_rom} -quiet] -quiet

# Block Designs: bd/mb_ddr3/mb_ddr3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3 || ORIG_REF_NAME==mb_ddr3} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_microblaze_0_axi_intc_0/mb_ddr3_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_ddr3_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_microblaze_0_xlconcat_0/mb_ddr3_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_ddr3_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_timer_0_0/mb_ddr3_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_timer_0_0 || ORIG_REF_NAME==mb_ddr3_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_uartlite_0_0/mb_ddr3_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_uartlite_0_0 || ORIG_REF_NAME==mb_ddr3_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_0/mb_ddr3_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_0_0 || ORIG_REF_NAME==mb_ddr3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_1_0/mb_ddr3_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_1_0 || ORIG_REF_NAME==mb_ddr3_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_2_0/mb_ddr3_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_2_0 || ORIG_REF_NAME==mb_ddr3_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_3_0/mb_ddr3_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_3_0 || ORIG_REF_NAME==mb_ddr3_axi_gpio_3_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_quad_spi_0_0/mb_ddr3_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_ddr3_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_microblaze_0_1/mb_ddr3_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_microblaze_0_1 || ORIG_REF_NAME==mb_ddr3_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_mig_7series_0_1/mb_ddr3_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_mig_7series_0_1 || ORIG_REF_NAME==mb_ddr3_mig_7series_0_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_dlmb_v10_1/mb_ddr3_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_dlmb_v10_1 || ORIG_REF_NAME==mb_ddr3_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_ilmb_v10_1/mb_ddr3_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_ilmb_v10_1 || ORIG_REF_NAME==mb_ddr3_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_dlmb_bram_if_cntlr_1/mb_ddr3_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_ddr3_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_ilmb_bram_if_cntlr_1/mb_ddr3_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_ddr3_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_lmb_bram_1/mb_ddr3_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_lmb_bram_1 || ORIG_REF_NAME==mb_ddr3_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_xbar_2/mb_ddr3_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_xbar_2 || ORIG_REF_NAME==mb_ddr3_xbar_2} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_13/mb_ddr3_auto_pc_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_13 || ORIG_REF_NAME==mb_ddr3_auto_pc_13} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_0/mb_ddr3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_0 || ORIG_REF_NAME==mb_ddr3_auto_pc_0} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_1/mb_ddr3_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_1 || ORIG_REF_NAME==mb_ddr3_auto_pc_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_2/mb_ddr3_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_2 || ORIG_REF_NAME==mb_ddr3_auto_pc_2} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_3/mb_ddr3_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_3 || ORIG_REF_NAME==mb_ddr3_auto_pc_3} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_4/mb_ddr3_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_4 || ORIG_REF_NAME==mb_ddr3_auto_pc_4} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_5/mb_ddr3_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_5 || ORIG_REF_NAME==mb_ddr3_auto_pc_5} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_6/mb_ddr3_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_6 || ORIG_REF_NAME==mb_ddr3_auto_pc_6} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_7/mb_ddr3_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_7 || ORIG_REF_NAME==mb_ddr3_auto_pc_7} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_8/mb_ddr3_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_8 || ORIG_REF_NAME==mb_ddr3_auto_pc_8} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_9/mb_ddr3_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_9 || ORIG_REF_NAME==mb_ddr3_auto_pc_9} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_10/mb_ddr3_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_10 || ORIG_REF_NAME==mb_ddr3_auto_pc_10} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_11/mb_ddr3_auto_pc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_11 || ORIG_REF_NAME==mb_ddr3_auto_pc_11} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_auto_pc_12/mb_ddr3_auto_pc_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_auto_pc_12 || ORIG_REF_NAME==mb_ddr3_auto_pc_12} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_microblaze_0_axi_periph_2/mb_ddr3_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_microblaze_0_axi_periph_2 || ORIG_REF_NAME==mb_ddr3_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_mdm_1_2/mb_ddr3_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_mdm_1_2 || ORIG_REF_NAME==mb_ddr3_mdm_1_2} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_rst_mig_7series_0_83M_2/mb_ddr3_rst_mig_7series_0_83M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_rst_mig_7series_0_83M_2 || ORIG_REF_NAME==mb_ddr3_rst_mig_7series_0_83M_2} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_1/mb_ddr3_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_0_1 || ORIG_REF_NAME==mb_ddr3_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_2/mb_ddr3_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_0_2 || ORIG_REF_NAME==mb_ddr3_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_3/mb_ddr3_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_0_3 || ORIG_REF_NAME==mb_ddr3_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_7/mb_ddr3_axi_gpio_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_0_7 || ORIG_REF_NAME==mb_ddr3_axi_gpio_0_7} -quiet] -quiet

# IP: bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_8/mb_ddr3_axi_gpio_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_ddr3_axi_gpio_0_8 || ORIG_REF_NAME==mb_ddr3_axi_gpio_0_8} -quiet] -quiet

# XDC: c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/mb_ddr3_ooc.xdc
