# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/yanxinj2/ECE385/Final/Final.runs/synth_1/mb_usb_hdmi_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yanxinj2/ECE385/Final/Final.cache/wt [current_project]
set_property parent.project_path C:/Users/yanxinj2/ECE385/Final/Final.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/yanxinj2/ECE385/RD_hdmi_ip2020 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/yanxinj2/ECE385/Final/Final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/yanxinj2/ECE385/don/don.COE
add_files C:/Users/yanxinj2/ECE385/bg/bg.COE
add_files C:/Users/yanxinj2/ECE385/katsu/katsu.COE
add_files C:/Users/yanxinj2/ECE385/org_chop.coe
add_files C:/Users/yanxinj2/ECE385/char1/char1.COE
add_files C:/Users/yanxinj2/ECE385/char2/char2.COE
add_files C:/Users/yanxinj2/ECE385/taiki/taiki.COE
read_verilog -library xil_defaultlib -sv {
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/sources_1/imports/design_source/Color_Mapper.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/sources_1/imports/design_source/VGA_controller.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/faded/audio.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/faded/audio_top.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/sources_1/imports/design_source/ball.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/bg/bg_example.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/bg/bg_palette.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/new/bgchange.sv
  C:/Users/yanxinj2/ECE385/char1/char1_example.sv
  C:/Users/yanxinj2/ECE385/char1/char1_palette.sv
  C:/Users/yanxinj2/ECE385/char2/char2_example.sv
  C:/Users/yanxinj2/ECE385/char2/char2_palette.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/new/charmove.sv
  C:/Users/yanxinj2/ECE385/don/don_example.sv
  C:/Users/yanxinj2/ECE385/don/don_palette.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/new/fifo_opt.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/sources_1/imports/design_source/hex_driver.sv
  C:/Users/yanxinj2/ECE385/katsu/katsu_example.sv
  C:/Users/yanxinj2/ECE385/katsu/katsu_palette.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/faded/music_rom.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/faded/pwm_gen.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/new/rand0_1.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/new/rand_generator.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/new/select_din.sv
  C:/Users/yanxinj2/ECE385/taiki/taiki_example.sv
  C:/Users/yanxinj2/ECE385/taiki/taiki_palette.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/faded/time_control.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/new/wait_ready.sv
  C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/sources_1/imports/design_source/mb_usb_hdmi_top.sv
}
read_ip -quiet c:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/char2_rom/char2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/char2_rom/char2_rom_ooc.xdc]

read_ip -quiet c:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/taiki_rom/taiki_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/taiki_rom/taiki_rom_ooc.xdc]

add_files C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/bd/mb_ddr3/mb_ddr3.bd
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_microblaze_0_axi_intc_0/mb_ddr3_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_microblaze_0_axi_intc_0/mb_ddr3_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_microblaze_0_axi_intc_0/mb_ddr3_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_timer_0_0/mb_ddr3_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_timer_0_0/mb_ddr3_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_uartlite_0_0/mb_ddr3_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_uartlite_0_0/mb_ddr3_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_uartlite_0_0/mb_ddr3_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_0/mb_ddr3_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_0/mb_ddr3_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_0/mb_ddr3_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_1_0/mb_ddr3_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_1_0/mb_ddr3_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_1_0/mb_ddr3_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_2_0/mb_ddr3_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_2_0/mb_ddr3_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_2_0/mb_ddr3_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_3_0/mb_ddr3_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_3_0/mb_ddr3_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_3_0/mb_ddr3_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_quad_spi_0_0/mb_ddr3_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_quad_spi_0_0/mb_ddr3_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_quad_spi_0_0/mb_ddr3_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_quad_spi_0_0/mb_ddr3_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_microblaze_0_1/mb_ddr3_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_microblaze_0_1/mb_ddr3_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_microblaze_0_1/mb_ddr3_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_mig_7series_0_1/mb_ddr3_mig_7series_0_1/user_design/constraints/mb_ddr3_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_mig_7series_0_1/mb_ddr3_mig_7series_0_1/user_design/constraints/mb_ddr3_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_dlmb_v10_1/mb_ddr3_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_ilmb_v10_1/mb_ddr3_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_dlmb_bram_if_cntlr_1/mb_ddr3_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_ilmb_bram_if_cntlr_1/mb_ddr3_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_lmb_bram_1/mb_ddr3_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_xbar_2/mb_ddr3_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_13/mb_ddr3_auto_pc_13_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_0/mb_ddr3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_1/mb_ddr3_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_2/mb_ddr3_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_3/mb_ddr3_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_4/mb_ddr3_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_5/mb_ddr3_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_6/mb_ddr3_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_7/mb_ddr3_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_8/mb_ddr3_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_9/mb_ddr3_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_10/mb_ddr3_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_11/mb_ddr3_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_auto_pc_12/mb_ddr3_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_mdm_1_2/mb_ddr3_mdm_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_mdm_1_2/mb_ddr3_mdm_1_2_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_rst_mig_7series_0_83M_2/mb_ddr3_rst_mig_7series_0_83M_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_rst_mig_7series_0_83M_2/mb_ddr3_rst_mig_7series_0_83M_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_rst_mig_7series_0_83M_2/mb_ddr3_rst_mig_7series_0_83M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_1/mb_ddr3_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_1/mb_ddr3_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_1/mb_ddr3_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_2/mb_ddr3_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_2/mb_ddr3_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_2/mb_ddr3_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_3/mb_ddr3_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_3/mb_ddr3_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_3/mb_ddr3_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_7/mb_ddr3_axi_gpio_0_7_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_7/mb_ddr3_axi_gpio_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_7/mb_ddr3_axi_gpio_0_7.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_8/mb_ddr3_axi_gpio_0_8_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_8/mb_ddr3_axi_gpio_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_axi_gpio_0_8/mb_ddr3_axi_gpio_0_8.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/mb_ddr3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_microblaze_0_1/data/mb_bootloop_le.elf]

read_ip -quiet C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/bg_rom/bg_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/bg_rom/bg_rom_ooc.xdc]

read_ip -quiet C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/don_rom/don_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/don_rom/don_rom_ooc.xdc]

read_ip -quiet C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/katsu_rom/katsu_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/katsu_rom/katsu_rom_ooc.xdc]

read_ip -quiet C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/fifo_generator_1/fifo_generator_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet c:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/ip/char1_rom/char1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/ip/char1_rom/char1_rom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/yanxinj2/ECE385/Final/Final.srcs/constrs_1/imports/ECE385/urbana_ddr3_provided/urbana_ddr3.xdc
set_property used_in_implementation false [get_files C:/Users/yanxinj2/ECE385/Final/Final.srcs/constrs_1/imports/ECE385/urbana_ddr3_provided/urbana_ddr3.xdc]

read_xdc C:/Users/yanxinj2/ECE385/Final/Final.srcs/constrs_1/imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc
set_property used_in_implementation false [get_files C:/Users/yanxinj2/ECE385/Final/Final.srcs/constrs_1/imports/ECE385/ece385-lab6-yanxinj2-qge3-1/lab6.2_new_proj/lab6.2_new_proj.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/yanxinj2/ECE385/Final/Final.srcs/utils_1/imports/synth_1/mb_usb_hdmi_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mb_usb_hdmi_top -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mb_usb_hdmi_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mb_usb_hdmi_top_utilization_synth.rpt -pb mb_usb_hdmi_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
