# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/bd/mb_ddr3/ip/mb_ddr3_xbar_2/mb_ddr3_xbar_2.xci
# IP: The module: 'mb_ddr3_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_xbar_2/mb_ddr3_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_ddr3_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/yanxinj2/ECE385/Final/Final.srcs/sources_1/bd/mb_ddr3/ip/mb_ddr3_xbar_2/mb_ddr3_xbar_2.xci
# IP: The module: 'mb_ddr3_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yanxinj2/ECE385/Final/Final.gen/sources_1/bd/mb_ddr3/ip/mb_ddr3_xbar_2/mb_ddr3_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_ddr3_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
